baseurl = "https://acearchive.lgbt/"
relativeUrls = true
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
section = ["HTML", "RSS", "SITEMAP"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  person = "people"
  identity = "identities"
  decade = "decades"

[permalinks]
  people = "/categories/people/:title/"
  identities = "/categories/identities/:title/"
  decades = "/categories/decades/:title/"
  archive = "/artifact/:filename/"

[minify.tdewolff.html]
  keepWhitespace = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "node_modules/@hyas/doks/archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/data"
    target = "data"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/katex"
    target = "assets/js/vendor/katex"
  [[module.mounts]]
    source = "node_modules/mermaid"
    target = "assets/js/vendor/mermaid"
  [[module.mounts]]
    source = "node_modules/@github/clipboard-copy-element"
    target = "assets/js/vendor/clipboard-copy-element"
  [[module.mounts]]
    source = "node_modules/mime"
    target = "assets/js/vendor/mime"
  [[module.mounts]]
    source = "node_modules/bootstrap"
    target = "assets/js/vendor/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map"
    target = "static/js/vendor/bootstrap/dist/js/bootstrap.bundle.min.js.map"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "data"
    target = "data"
