# The maximum number of names to display on each card in the artifacts list
# view.
maxPeoplePerCard: 4

# The URL of the OpenAPI spec for rendering the API docs.
openapiSpecUrl: "https://raw.githubusercontent.com/acearchive/api-worker/main/openapi.yaml"

# If the URL of a link in an artifact has one of these domain names, it will be
# marked as an archive link.
archiveLinkDomains:
  - "web.archive.org"
  - "replayweb.page"

#
# Metadata for SEO
#

# Homepage
title: "Ace Archive"
headerLogo: "/images/logo-transparent.webp"
headerLogoAlt: "The Ace Archive logo, a rainbow file box"
titleSeparator: "-"
titleAddition: "Asexual and aromantic history"
description: >-
  Ace Archive is a curated online archive of asexual and aromantic history.

# Open Graph
images: ["images/logo-card.webp"]
ogLocale: "en_US"
domainTLD: "acearchive.lgbt"
titleHome: "Ace Archive"

# JSON-LD
schemaType: "Organization"
schemaName: "Ace Archive"
schemaAuthor: "Frawley"
schemaAuthorGitHub: "https://github.com/frawleyskid"
schemaLocale: "en-US"
schemaLogo: "images/logo-transparent.webp"
schemaLogoWidth: 912
schemaLogoHeight: 912
schemaImage: "images/logo-card.webp"
schemaImageWidth: 2560
schemaImageHeight: 1280
schemaGitHub: "https://github.com/acearchive"

# Sitelinks search box
siteLinksSearchBox: false

# Chromium browser
themeColorLight: "#fff" # $body-bg
themeColorDark: "#212529" # $body-bg-dark

# Images
quality: 100
bgColor: "#fff"
landscapePhotoWidths: [900, 800, 700, 600, 500]
portraitPhotoWidths: [800, 700, 600, 500]
lqipWidth: "20x"
smallLimit: "300"
logoBackgroundFill: "#fff"

# Footer
footer: 'Powered by <a href="https://gohugo.io/">Hugo</a> and <a href="https://getdoks.org/">Doks</a>'

# Feed
copyRight: "Copyright © 2022-2023 Frawley"

# Alert
alert: false
alertDismissable: true
alertText: ""

# Edit page
docsRepo: "https://github.com/acearchive/acearchive.lgbt"
docsRepoBranch: "main"
editPage: true

# Feature flags
options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  darkMode: true
  bootStrapJs: true
  breadCrumb: false
  highLight: true
  collapsibleSidebar: true
  multilingualMode: false
  docsVersioning: false
