name: Suggest Content
description: Suggest content to be added to the archive.
labels: ["artifact"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for your interest in Ace Archive! This is a form for suggesting
        content to be added to the archive. Alternatively, if you want to
        contribute to the archive yourself, you can [read the
        documentation](https://acearchive.lgbt/docs/contributing/getting-started)
        on opening a pull request!
  - type: textarea
    id: context
    attributes:
      label: "Context and significance"
      description: >
        What is the content you're suggesting be added to the archive? Why is
        it significant to the aspec community? Why should it be included in the
        archive?
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: "Sources"
      description: >
        Where can we find this content? Please provide URLs. In the case of
        published works, we prefer more authoritative sources like journal
        databases, libraries, and archives like the Internet Archive, but this
        can also be as simple as a link to a forum thread or a blog post. If
        the content isn't accessible or is written in a language other than
        English, consider whether a transcript or a translation are available.
        If the content isn't available on the web anymore, [Wayback
        Machine](https://web.archive.org/) links are fine!
    validations:
      required: true
  - type: input
    id: people
    attributes:
      label: "People"
      description: >
        List 1-3 significant people associated with this content, if
        applicable. It could be the author of a book, a commenter in a forum
        thread, or the subject of a photo.
  - type: input
    id: identities
    attributes:
      label: "Identities"
      description: >
        List any specific queer identities associated with this content. Is
        this a blog post about non-binary people? A book about aromanticism?
  - type: input
    id: years
    attributes:
      label: "Years"
      description: >
        When was this content published/written/posted? This can be a range of
        years.
  - type: textarea
    id: extra
    attributes:
      label: "Anything else"
      description: >
        Is there anything else you want to mention?
