name: "Deploy"

on: [push]

jobs:
  dev:
    name: "Deploy (dev)"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: "Install"
        working-directory: ./site/
        run: npm ci

      - name: "Sync Artifacts"
        working-directory: ./site/
        run: npm run sync:dev

      - name: "Build"
        working-directory: ./site/
        run: npm run build:dev

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v3
        with:
          environment: dev
          workingDirectory: ./site/
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  prod:
    name: "Deploy (prod)"
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: "Install"
        working-directory: ./site/
        run: npm ci

      - name: "Sync Artifacts"
        working-directory: ./site/
        run: npm run sync:prod

      - name: "Build"
        working-directory: ./site/
        run: npm run build:prod

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v3
        with:
          environment: prod
          workingDirectory: ./site/
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
