name: "Upload artifacts"

concurrency: "upload-artifacts"

on:
  workflow_dispatch:
  push:
    paths: ["content/archive/*/index.md"]
    branches: ["main"]

jobs:
  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: "ipfs/go-ipfs:latest"
        ports:
          - 4001:4001
          - 5001:5001
          - 8080:8080
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Upload"
        uses: acearchive/artifact-action@main
        with:
          w3s-token: ${{ secrets.W3S_API_TOKEN }}
          ipfs-api: "/dns/ipfs/tcp/5001/http"
