name: "Validate artifacts"

on:
  workflow_dispatch:
  pull_request:
    paths: ["content/archive/*/index.md"]

jobs:
  archive:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate"
        uses: acearchive/w3s-upload@main
        with:
          path-glob: "content/archive/*/index.md"
          upload: false


